### ISSUE TITLE
只写class不写package和action

### ISSUE THREAD

**Issue by ipcjs** [greenify/greenify.github.io#1]
使用绿色守护自带的唤醒剪断功能，显示酷安App被唤醒的方式是：`com.xiaomi.mipush.sdk.PushMessageHandler`，然后我反编译apk，这个类对应的清单文件如下：
```xml
<service
  android:enabled="true"
  android:exported="true"
  android:name="com.xiaomi.mipush.sdk.PushMessageHandler" /> 
```
没有action。。。然后我写了如下`处方1`：
```xml
<prescription xmlns="http://greenify.github.io/schemas/prescription/v1" 
    type="service" 
    class="com.xiaomi.mipush.sdk.PushMessageHandler" >
</prescription>
```
导入时提示不合法。。。加上package之后，导入成功，<code><a href="https://greenify.github.io/ipcjs/rx-mipush">处方2</a></code>如下：

```xml
<prescription xmlns="http://greenify.github.io/schemas/prescription/v1" 
    type="service" 
    class="com.xiaomi.mipush.sdk.PushMessageHandler" 
    package="com.coolapk.market">
</prescription>
```
Nexus5+CM14.1上实测，可以拦截对酷安App的唤醒。

但`处方2`写死了package，只对酷安App有效，对使用了同类推送SDK的App无效。
要是绿色守护支持`处方1`那种写法，就方便多了，不知道实现起来麻不麻烦？

**Comment by oasisfeng** [comment]
很遗憾，处方1虽然也是我一开始就希望支持的形式，但由于Android底层机制的制约，暂时还无法实现。

不过我已经想到了一个变通支持这种形式的办法，春节后会原型验证一下，再更新到这里。

**Comment by oasisfeng** [comment]
从编写一个高质量处方的角度，一般并不建议完全屏蔽整个组件。最好能限定intent-filter进行屏蔽（这也是目前已经支持的形式），这样可以避免误伤该组件所支撑的其它重要功能。Greenify未来的版本中将提供这方面的详细线索，比如具体触发唤醒的intent，便于大家编写更精准的处方。

**Comment by liudongmiao** [comment]
如果说处方底层采用`IntentFirewall`的话，我不明白，什么叫“Android底层机制的制约”，不是有`component-filter`么？但这种模式下，我在想，你怎么绕过权限处理的呢？这个是需要  system 权限才能写...希望不是一般的普通权限就能处理的方式，要不然，你能写，别的应用同样可以。

如果不是`IntentFirewall`的话，看起来工作方式又很像。

**Comment by ipcjs** [comment]
原来是用[IntentFirewall.java](https://android.googlesource.com/platform/frameworks/base/+/633dc9b/services/java/com/android/server/firewall/IntentFirewall.java)实现的功能~~

@liudongmiao 看文档([Intent Firewall - Main Page](http://www.cis.syr.edu/~wedu/android/IntentFirewall/))，貌似`component-filter`一定要写包名的样子

**Comment by liudongmiao** [comment]
我更担心，这个功能对生态的影响。

根据底层实现代码，在5.1之前，校验版本，内容hash：https://android.googlesource.com/platform/frameworks/base/+/android-5.1.1_r38/services/core/java/com/android/server/updates/ConfigUpdateInstallReceiver.java

也就是说，一旦加上，就没有退出机制。当然，不排除绿色守护底层不使用这个机制，而是其他的权限绕过。

从意义上讲，这个写成一个简单的应用更合适。

**Comment by liudongmiao** [comment]
@ipcjs，有`component-name-filtet`的：android.googlesource.com/platform/frameworks/base/+/android-5.1.1_r38/services/core/java/com/android/server/firewall/StringFilter.java

**Comment by ipcjs** [comment]
@liudongmiao 看了半天源码才大概搞懂逻辑_(:3」∠)_，要过滤组件类名貌似应该这么写：
```xml
<rules>
  <activity block="true" log="true">
    <component-name equals="com.xiaomi.mipush.sdk.PushMessageHandler"/>
  </activity>
</rules>
```

**Comment by ipcjs** [comment]
顶了半天源码，总算了解了大概的逻辑_(:3」∠)_
@liudongmiao 看[IntentFirewall.checkIntent()](https://android.googlesource.com/platform/frameworks/base/+/android-5.1.1_r38/services/core/java/com/android/server/firewall/IntentFirewall.java#145)的源码，一定要先匹配到`intent-filter`或`component-filter`才会执行之后的[rule.matches()](https://android.googlesource.com/platform/frameworks/base/+/android-5.1.1_r38/services/core/java/com/android/server/firewall/IntentFirewall.java#164)，去匹配`component-name`、`component-package`等其他标签

**Comment by oasisfeng** [comment]
@liudongmiao 不是很明白你提到的“没有退出机制”？这里不存在任何独占，你再仔细读读AOSP相关源码。

**Comment by liudongmiao** [comment]
@oasisfeng 

如果是以 IntentFirewallInstallReceiver 这种广播形式实现的话，有可能会对系统造成永久性“后遗症”。

根据源码：https://android.googlesource.com/platform/frameworks/base/+/android-5.1.1_r38/services/core/java/com/android/server/updates/IntentFirewallInstallReceiver.java 每次改动之后，会校验上一次写入的版本号与文件内容。也就是说，基本上只有一个应用能写了，因为其它的应用并不能读取这个文件内容，也不能读取相应的版本号。

**Comment by oasisfeng** [comment]
@liudongmiao 不是这样的。虽然有校验，但内容的校验不是必须的，而版本号有足够大的空间（1~2147483648），并不会因为某个app使用了就没有其它app的使用空间。

当然，不排除某个app恶意写入了太大的版本号导致版本空间耗尽。

**Comment by liudongmiao** [comment]
@oasisfeng 确实是我忽略了，没有点进去看内容校验的实现，里面居然写着 "NONE" ....
