### ISSUE TITLE
对“酷安”(CoolApk)启动图的拦截问题

### ISSUE THREAD

**Issue by WitherZuo** [greenify/greenify.github.io#2]
更新的酷安v7版本，新增了启动图(即酷图)，应用里面没有提供关闭选项，于是我写了一个用于酷图拦截的处方

经检查酷图的activity是com.coolapk.market.view.photo.SplashActivity
但是导入并激活后并没有屏蔽掉酷图，导入处方时绿色守护也没有任何错误信息，不知这是为何。
`<prescription xmlns="http://greenify.github.io/schemas/prescription/v2"
`
` type="activity"`
` sender="any"`
` package="com.coolapk.market"`
` class="com.coolapk.market.view.photo.SplashActivity">`
`</prescription>`

**Comment by oasisfeng** [comment]
经实测有效。导入 https://github.com/WitherZuo/rx-coolapk-nosplash 后，酷安app不再显示启动图。关闭处方后，启动图再次显示。

不过目前的3.2.1版本有个bug，每次修改后的第一遍部署不会生效。你可以关闭&打开任意处方后，再次点击『生效』按钮重新部署一遍，就可以生效了。下个版本将会修复这个bug。

**Comment by WitherZuo** [comment]
谢谢Oasis大大，我再试试看，晚安！
