### ISSUE TITLE
导入处方集时发现出现异常

### ISSUE THREAD

**Issue by simonsmh** [greenify/greenify.github.io#5]
导入时发现出现内部异常 [link](https://github.com/simonsmh/rxs-colle/blob/master/rxs-colle.xml)
此外，单独导入后更新处方时也会出现内部异常。

**Comment by oasisfeng** [comment]
这可能是由于一个已知问题引起，请在即将发布的新版本上验证后回报。

**Comment by WitherZuo** [comment]
请问Google Play上搜索不到绿色守护，只存在捐赠包，是下架了吗？

**Comment by oasisfeng** [comment]
@WitherZuo 一个小误会，参见我的Twitter。

**Comment by oasisfeng** [comment]
这个问题在3.2.2中应已修复，如果仍有问题，请回报。

**Comment by simonsmh** [comment]
可3.2.2是上个月的更新啊。。

**Comment by simonsmh** [comment]
依然存在问题。。
规则也已经更到v3了

**Comment by oasisfeng** [comment]
这是由于其中的rx-tpush、rx-huaweipush这俩repo没有description造成的，请反馈给作者补充repo描述。

下个版本将加上对description为空的保护。
